[versions]
agp = "8.5.2"
kotlin = "1.9.10"
kotlinKsp = "1.9.10-1.0.13"
hilt = "2.52"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlinKsp" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}